export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const OPEN_CURRENT_PRODUCT = "OPEN_CURRENT_PRODUCT";

export const SEND_DELETE_ERROR = "SEND_DELETE_ERROR";
export const SEND_DELETE_SUCCESS = "SEND_DELETE_SUCCESS";
export const SEND_DELETE_REQUEST = "SEND_DELETE_REQUEST";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";

export const DELETE_ORDER = "DELETE_ORDER";